language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:

    # rename the cloned folder
    - cd .. && mv $NODE_LABELS COBRA && cd COBRA

    # launch the tests
    - bash .artenolis/runtests.sh

after_success:
    - /mnt/prince-data/JULIA/$JULIA_VER/bin/julia --color=yes -e 'cd(Pkg.dir("COBRA")); using Coverage; Codecov.submit_generic(process_folder(), verbose=false);'