language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:

    # launch the tests
    - bash .artenolis/runtests.sh

    # launch the tests
    #- /mnt/prince-data/JULIA/$JULIA_VER/bin/julia -e 'println(versioninfo()); exit()'

    #- bash .artenolis/runtests.sh

