language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:

    # rename the cloned folder
    - cd .. && mv linux COBRA && cd COBRA

    # launch the tests
    - bash .artenolis/runtests.sh
