language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    #- nightly
notifications:
    email: false
sudo: required
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev

git:
    depth: 99999

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
    # update all packages
    - julia --color=yes -e 'Pkg.update();'

    # add the COBRA module
    - julia --color=yes -e 'Pkg.clone(pwd())'
    - julia --color=yes -e 'Pkg.build("COBRA")'
    - julia --color=yes -e 'Pkg.test("COBRA",coverage=true)'

after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'cd(Pkg.dir("COBRA")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(Coveralls.process_folder())'
    - julia -e 'cd(Pkg.dir("COBRA")); Pkg.add("Documenter"); include(joinpath("docs", "makeDoc.jl"))'
